# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4bb74ce990858b3304bb96edfd0a7677936109791196c234fb5c19a3256806ae9bc051fcfa8ccb36eeb99dbd7ae1e4525d0794c41b8fe27911fe4eb7abc7e28c

test:
  secret_key_base: 63d7386f726afce471e7024d27dcef5d9958b5621c8b47755315bd31421516ff43087a660ddc9dd29a9385eb5f4ae6e1cd6b6a05f5aaf836a6a5332038392657

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
